[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  SECRETS_SCAN_OMIT_KEYS = "BIGQUERY_PROJECT_ID,BIGQUERY_DATASET,GOOGLE_MAPS_API_KEY,GOOGLE_PLACE_ID"

[dev]
  command = "npm run dev"
  port = 5173
  functionsPort = 9999

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"