[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "BIGQUERY_PROJECT_ID,BIGQUERY_DATASET"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
